name: CD

on: 
  push:
    branches: [main]  

jobs:  
  steps:    
    - name: zip file
        run: zip -r kaera.zip ./dist ./scripts ./appspec.yml ./.env ./package.json ./prisma

    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: upload to S3
      run: aws s3 cp --region ap-northeast-2 ./kaera.zip s3://kaera-build/deploy/

    - name: deploy with AWS codeDeploy
      run: aws deploy create-deployment
        --application-name kaera-codedeploy
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name GROUP
        --s3-location bucket=kaera-build,bundleType=zip,key=deploy/kaera.zip